# -*- coding: utf-8 -*-
"""pie_charts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yqx5wBOJwT7NYB0o1L-HWkBpd7AZXCdq
"""

# 한글 폰트(나눔 폰트) 설치
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# 설치된 폰트를 matplotlib에 적용
plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False # 마이너스 기호 깨짐 방지

import matplotlib.pyplot as plt

# 폰트 설정 재확인 (한글 폰트 적용)
plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

# 1. File 1: final_log.json[cite: 1]
file1_labels = ['파이썬 (Python)', '안드로이드 스튜디오 (studio64)', 'VS Code (code)']
file1_sizes = [46, 35, 14]

# 2. File 2: laptop_log.json[cite: 2]
file2_labels = ['안드로이드 스튜디오', '파이썬', 'VS Code', '대기 (idle)']
file2_sizes = [13, 11, 7, 3]

# 3. File 3: state_log.json[cite: 3]
file3_labels = ['앉아있기 (SITTING)', '서있기 (STANDING)']
file3_sizes = [33.7, 5.8]

# 4. File 4: summary_log.json[cite: 4]
file4_labels = ['걷기 (Walking)', '운동 (Exercising)', '팔 운동 (Arm Exercise)', '독서 (Reading)']
file4_sizes = [7, 4, 2, 1]

# 5. File 5: transition_log.json[cite: 5]
file5_labels = ['행동 전환 (Activity)', '자세 전환 (Posture)']
file5_sizes = [11, 2]

# 시각화 설정 (2행 3열)
fig, axs = plt.subplots(2, 3, figsize=(18, 11)) # 라벨 공간 확보를 위해 세로 길이 소폭 증가
fig.suptitle('통합 행동 및 디지털 로그 대시보드', fontsize=20, fontweight='bold', y=1.05)

# 차트 및 총합 그리기 함수
def draw_pie(ax, sizes, labels, title, unit, colors=None):
    # 이름 아래에 값과 단위를 추가하도록 레이블 수정 (\n 줄바꿈 사용)
    detailed_labels = [f"{label}\n({size}{unit})" for label, size in zip(labels, sizes)]

    # 원형 그래프 그리기 (수정된 detailed_labels 적용)
    ax.pie(sizes, labels=detailed_labels, autopct='%1.1f%%', startangle=140, colors=colors, shadow=True)
    ax.set_title(title, fontsize=12, fontweight='bold')

    # 총합 계산
    total = sum(sizes)

    # 소수점 여부에 따라 텍스트 포맷 조정
    if isinstance(total, float):
        total_text = f"총 합계: {total:.1f} {unit}"
    else:
        total_text = f"총 합계: {total} {unit}"

    # 그래프 하단에 총합 텍스트 표시
    ax.set_xlabel(total_text, fontsize=13, fontweight='bold', color='#333333')

# [1] 최종 디지털 앱 누적 시간 비율 (단위: 초)[cite: 1]
draw_pie(axs[0, 0], file1_sizes, file1_labels, '1. final_log: 디지털 앱 누적 사용 시간', '초', ['#ffeb3b', '#03a9f4', '#8bc34a'])

# [2] 노트북 포그라운드 앱 이벤트 발생 비율 (단위: 회)[cite: 2]
draw_pie(axs[0, 1], file2_sizes, file2_labels, '2. laptop_log: 포그라운드 앱 활성화 빈도', '회', ['#03a9f4', '#ffeb3b', '#8bc34a', '#e0e0e0'])

# [3] 기본 자세 유지 시간 비율 (단위: 초)[cite: 3]
draw_pie(axs[0, 2], file3_sizes, file3_labels, '3. state_log: 기본 자세 유지 시간 비율', '초', ['#ff9999', '#66b3ff'])

# [4] 세부 물리 행동 시간 비율 (단위: 초)[cite: 4]
draw_pie(axs[1, 0], file4_sizes, file4_labels, '4. summary_log: 세부 물리 행동 누적 시간', '초', ['#ffb3e6', '#ffcc99', '#c2c2f0', '#99ff99'])

# [5] 행동 및 자세 전환 유형 비율 (단위: 회)[cite: 5]
draw_pie(axs[1, 1], file5_sizes, file5_labels, '5. transition_log: 상태 전환 발생 유형', '회', ['#ffb3e6', '#ff9999'])

# 6번째 빈 공간(axs[1, 2]) 숨김 처리
axs[1, 2].axis('off')

plt.tight_layout()
plt.show()